project_id = "ccsweamqyoalxkyuqkfm"

[functions.chat]
verify_jwt = false

[functions.gpt-chat]
verify_jwt = false

[functions.code-assistant]
verify_jwt = false

[functions.analyze-file]
verify_jwt = false

[functions.image-generation]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.web-search]
verify_jwt = false

[functions.wikipedia]
verify_jwt = false